import Head from 'next/head'
import Image from 'next/image'
import DetailsPage from '../components/chics/DetailsPage'
import SectionOne from '../components/club/SectionOne'
import LSectionOne from '../components/landing/LSectionOne'
import LSectionTwo from '../components/landing/LSectionTwo'
import Navbar from '../components/navbar/Nabar'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className='home-page'>
      {/* <Head>
        <title>Escort</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"></link>

      </Head> */}

      <Navbar />
      <LSectionOne />
      <LSectionTwo />
      <SectionOne />

      
      {/* <DetailsPage />
      <SectionOne />      */}
    </div>
  )
}
